version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    entrypoint: >
      /bin/sh -c "
      while ! nc -z minio 9000; do sleep 1; done;
      mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      mc mb myminio/my-bucket;
      mc policy set public myminio/my-bucket;
      "
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: minio-cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    # networks:
    #   - iuhkart-network
    depends_on:
      - minio