services:
    superset:
        init: true
        build: 
            context: ./configs/superset
            dockerfile: Dockerfile
        container_name: superset
        restart: unless-stopped
        ports:
            - "8088:8088"
        environment:
            SUPERSET_ENV: production
            SUPERSET_LOAD_EXAMPLES: "yes"
            SUPERSET_DATABASE_URI: postgresql+psycopg2://${DBUSER}:${PASSWORD}@${HOST}:${PORT}/${NAME}
            SECRET_KEY: ${SECRET_KEY}
        networks:
            - iuhkart-network
        depends_on:
            - superset-db
        volumes:
            - ./configs/superset/superset_config.py:/app/superset_config.py
        healthcheck:
            test: ["CMD", "curl", "-f", "http://superset:8088/health"]
            interval: 30s
            timeout: 10s
            retries: 5

networks:
    iuhkart-network:
        name: iuhkart-network
        external: true

