# Generated by Django 5.0.2 on 2024-05-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('product_discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.ForeignKey(db_column='discount_id', on_delete=django.db.models.deletion.CASCADE, to='discount.discount')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_discount',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(through='discount.ProductDiscount', to='product.product'),
        ),
        migrations.CreateModel(
            name='OrderProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discount')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderproduct')),
            ],
            options={
                'db_table': 'order_product_discount',
                'unique_together': {('order_product', 'discount')},
            },
        ),
        migrations.AddIndex(
            model_name='productdiscount',
            index=models.Index(fields=['start_date'], name='product_dis_start_d_098250_idx'),
        ),
        migrations.AddIndex(
            model_name='productdiscount',
            index=models.Index(fields=['end_date'], name='product_dis_end_dat_596c75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productdiscount',
            unique_together={('product', 'discount')},
        ),
    ]
