networks:
    iuhkart-network:
        name: iuhkart-network
        external: true

services:
    cloudflare:
        image: cloudflare/cloudflared:latest
        container_name: database-cloudflare
        restart: always
        command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
        networks:
            - iuhkart-network
        depends_on:
            - minio

    postgres-database:
        image: postgres:17.0
        container_name: postgres-database
        environment:
            POSTGRES_USER: iuhkart
            POSTGRES_PASSWORD: iuhkartpassword
            POSTGRES_DB: postgres
        command: [ "postgres", "-c", "wal_level=logical" ]
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres-data:/data/postgres
            - ./configs/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
        networks:
            - iuhkart-network
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "iuhkart"]
            interval: 10s
            timeout: 5s
            retries: 5

    # chưa tạo được replSet để connect debezium
    # mongodb:
    #     container_name: mongodb
    #     image: mongo:7.0.2
    #     restart: always
    #     ports:
    #         - 27017:27017
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: iuhkart
    #         MONGO_INITDB_ROOT_PASSWORD: iuhkartpassword
    #         MONGO_INITDB_DATABASE: mydb
    #     command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    #     networks:
    #         - iuhkart-network
    #     volumes:
    #         - ./configs/mongo/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js:ro
    #         - ./data/mongo-data:/data/db
    #         # - ./configs/mongo-key:/etc/mongo/mongo-key:ro
    #         # - ./configs/mongo-config:/data/configdb
    #     healthcheck:
    #         test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5

    qdrant:
        container_name: qdrant
        image: qdrant/qdrant:v1.12.1
        ports:
            - 6334:6333
        volumes:
            - ./data/qdrant-data:/qdrant/storage
        networks:
            - iuhkart-network
        restart: always
        healthcheck:
            test:
                - CMD-SHELL
                - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
            interval: 5s
            timeout: 5s
            retries: 3

    clickhouse:
        image: 'clickhouse/clickhouse-server:24.7-alpine'
        container_name: 'clickhouse-server'
        hostname: clickhouse
        ports:
            - '8123:8123'
            - '9000:9000'
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            - './configs/clickhouse/config.xml:/etc/clickhouse-server/config.xml'
            - './configs/clickhouse/users.xml:/etc/clickhouse-server/users.xml'
        networks:
            - iuhkart-network
        restart: always
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://clickhouse:8123/ping || exit 1
            interval: 10s
            timeout: 5s
            retries: 5

    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        ports:
            - "29000:9000"
            - "9001:9001"
        environment:
        MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
        MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
        volumes:
            - ./data/.minio.sys:/data/.minio.sys
        command: server /data --console-address ":9001"

    mc:
        image: minio/mc:latest
        container_name: minio-mc
        depends_on:
            - minio
        environment:
            MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
            MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
        entrypoint: >
            /bin/sh -c "
            while ! nc -z minio 9000; do sleep 1; done;
            mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
            mc mb myminio/my-bucket;
            mc policy set public myminio/my-bucket;
            "
    