version: '3.0'
services:
  qdrant_db:
    image: qdrant/qdrant:v1.4.1
    ports:
      - "6336:6333"
    networks:
      - iuhkart-network
    volumes:
      - ./qdrant-db-volume:/qdrant/storage
    restart: unless-stopped

  fastapi:
    build: app
    ports:
      - "8008:8000"
    env_file:
      - .env
    working_dir: /app
    command: uvicorn main:app --host "0.0.0.0" --port 8000 --reload
    networks:
      - iuhkart-network
    depends_on:
      - qdrant_db
    volumes:
      - ./app:/app
    restart: unless-stopped

  iuhkart_cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: iuhkart-cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiODZlYTNjZjEwNmRlMTU3Yjc2NTg0YzgyODgyNDdmMTciLCJ0IjoiMjkwNDAwODQtZmM4NS00YmFhLTk1OTUtODA0NDc3ZTY1OTA3IiwicyI6IlpqZzFaV0UwWm1JdFpESTBNaTAwTUdSaExUZ3habVV0WVdaa05UazNOV0kyTVdVMSJ9

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    networks:
      - iuhkart-network
    volumes:
      - metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    restart: unless-stopped

networks:
  iuhkart-network:
    name: iuhkart
    driver: bridge

volumes:
  metabase-data:
