services:
  tracking_api:
    container_name: tracking-api
    build: 
      context: ./tracking-api
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    env_file:
      - .env
    working_dir: /app
    networks:
      - iuhkart-network
    volumes:
      - ./tracking-api:/app
    restart: unless-stopped

  search_api:
    container_name: search-api
    build:
      context: ./search-api
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    env_file:
      - .env
    working_dir: /app
    networks:
      - iuhkart-network
    volumes:
      - ./search-api:/app
    restart: unless-stopped

  

  django_main:
    build: ./iuhkart
    ports:
      - "8009:8000"
    env_file:
      - .env
    working_dir: /app
    networks:
      - iuhkart-network
    volumes:
      - ./iuhkart:/app
    restart: unless-stopped

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: iuhkart-cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
    networks:
      - iuhkart-network
    depends_on:
      - django_main
      - search_api
      - tracking_api
  
  # vendor_fe:
  #   build: ./iuhkart-vendor
  #   ports:
  #     - "8006:8000"
  #   env_file:
  #     - ./iuhkart-vendor/.env
  #   working_dir: /app
  #   networks:
  #     - iuhkart-network
  #   depends_on:
  #     - django_main
  # customer_fe:
  #   build: ./iuhkart-customer
  #   ports:
  #     - "8005:8000"
  #   env_file:
  #     - ./iuhkart-customer/.env
  #   working_dir: /app
  #   networks:
  #     - iuhkart-network
  #   depends_on:
  #     - django_main
  
networks:
  iuhkart-network:
    name: iuhkart-network
    external: true
